### ISSUE TITLE
Can't deploy source to Org

### ISSUE THREAD

**Issue by A-Tahemmout** [trailheadapps/visualforce-to-lwc#279]
### Summary

When wanting to deploy source to org, I get this error message :
```
lwc/navigateToRecord/navigateToRecord.js-meta.xml: This component doesn't support any target for flows, but it's referenced in these flow versions: 'Create Property-1'. Add any of these targets to the component: 'lightning__FlowScreen'. 
lwc/navigateToRecord/navigateToRecord.js-meta.xml: You can’t change the isExposed property to ‘false’ because the component is part of a managed package.
lwc/navigateToRecord/navigateToRecord.js-meta.xml: This component doesn't support any target for flows, but it's referenced in these flow versions: 'Create Property-1'. Add any of these targets to the component: 'lightning__FlowScreen'. 
lwc/navigateToRecord/navigateToRecord.js-meta.xml: You can’t change the isExposed property to ‘false’ because the component is part of a managed package.
```

Config:
"path": "force-app",
"default": true,
"package": "vf2lwc",
"versionName": "Spring '22",
"versionNumber": "54.0.0.NEXT"

### Salesforce Org Type

Trailhead Playground

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by albarivas** [comment]
Hi, I just tried it out and works for me. There are no flows in this repo, or any flow reference, so make sure you're not mixing the code with something else. Examine the navigateToRecord LWC- it shouldn't have a dependency with flow. Kind regards.
