### ISSUE TITLE
There is no permission set named "Walkthroughs"

### ISSUE THREAD

**Issue by msrivastav13** [trailheadapps/visualforce-to-lwc#91]
### Summary

The readme file says there is another permission set named "Walkthroughs". I could not find them anywhere.

### Steps To Reproduce:

1.  Read Read me file
2. Fix if needed

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot or code snippets_.

**Comment by albarivas** [comment]
The Walkthroughs permission set gets created when you activate in-app prompts. Makes sense?

**Comment by msrivastav13** [comment]
Maybe we want to add instructions in the note for it.

`A walkthroughs permission set gets auto-created on clicking the Start Walkthrough Trial button on the In-App Guidance Setup page `
